name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check:
    name: Checks
    runs-on: [self-hosted, heavy]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run checks
        run: make check
      - name: Run tests
        run: make test
