name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check:
    name: Checks
    runs-on: [self-hosted, heavy]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run all checks
        run: make check
  test:
    name: Tests
    runs-on: [self-hosted, heavy]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Add toolchain target
        run: rustup target add wasm32-unknown-unknown
      - name: Restore cache
        run: |
          cache-util restore cargo_git cargo_registry
      - name: Run tests
        run: make test
      - name: Save cache
        run: |
          cache-util save cargo_git cargo_registry
