name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check:
    name: Checks
    runs-on: [self-hosted, heavy]
    steps:
      - name: Install rust
        run: |
          rustup show
          rustup default ${{ env.RUST_VERSION }}
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Run all checks
        run: make check
  test:
    name: Tests
    runs-on: [self-hosted, heavy]
    steps:
      - name: Install rust
        run: |
          rustup show
          rustup default ${{ env.RUST_VERSION }}
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Restore cache
        run: |
          cache-util restore cargo_git cargo_registry
      - name: Run tests
        run: make test
      - name: Save cache
        run: |
          cache-util save cargo_git cargo_registry

env:
  RUST_VERSION: 1.80.0
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
