name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  check:
    name: Checks
    runs-on: [self-hosted, heavy]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run all checks
        run: make check
  test:
    name: Tests
    runs-on: [self-hosted, heavy]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Add toolchain
        run: rustup target add wasm32-unknown-unknown
      - name: Restore cache
        run: |
          cache-util restore cargo_git cargo_registry sandbox:${{ env.NEAR_SANDBOX_BIN_PATH }}
      - name: Install sandbox
        run: |
          if [[ ! -f ${{ env.NEAR_SANDBOX_BIN_PATH }} ]]; then
            mkdir -p $HOME/bin
            rm -rf nearcore
            git clone --depth 1 --branch 1.35.0 https://github.com/near/nearcore
            cd nearcore
            make sandbox-release
            cp target/release/near-sandbox $HOME/bin/
            cache-util save sandbox:${{ env.NEAR_SANDBOX_BIN_PATH }}          
            cd ../
            rm -rf nearcore
          fi
      - name: Run tests
        run: NEAR_SANDBOX_BIN_PATH=${{ env.NEAR_SANDBOX_BIN_PATH }} make test
      - name: Save cache
        run: |
          cache-util save cargo_git cargo_registry

env:
  NEAR_SANDBOX_BIN_PATH: $HOME/bin/near-sandbox
